language: node_js
node_js:
  - "0.12"

branches:
  only:
    - master

before_install:
  - npm install gulp -g

script:
  - npm install

cache:
  directories:
  - vendor
  - node_modules