language: node_js
node_js:
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

branches:
  only:
    - master

before_install:
  - npm install gulp -g

script:
  - npm install

cache:
  directories:
  - vendor
  - node_modules